project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercises 1"
          href: "Hands-on_Ex/Hands-on_Ex01/hands_on1.html"
        - text: "Hands-on Exercises 2"
          href: "Hands-on_Ex/Hands-on_Ex02/hands_on2.html"
        - text: "Hands-on Exercises 3-1"
          href: "Hands-on_Ex/Hands-on_Ex03/hands_on3-1.html"
        - text: "Hands-on Exercises 3-2"
          href: "Hands-on_Ex/Hands-on_Ex03/hands_on3-2.html"
        - text: "Hands-on Exercises 4"
          href: "Hands-on_Ex/Hands-on_Ex04/hands_on4.html"
        - text: "Hands-on Exercises 5"
          href: "Hands-on_Ex/Hands-on_Ex05/hands_on5.html"
          
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/ICE_01/ice_01.html"
        - text: "In-class Exercise 2"
          href: "In-class_Ex/ICE_02/ice_02.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/ICE_03/ice_03.html"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/ICE_04/ice_04.html"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

