project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercises 1"
          href: "Hands-on_Ex/Hands-on_Ex01/hands_on1.html"
        - text: "Hands-on Exercises 2"
          href: "Hands-on_Ex/Hands-on_Ex02/hands_on2.html"
        - text: "Hands-on Exercises 3-1"
          href: "Hands-on_Ex/Hands-on_Ex03/hands_on3-1.html"
        - text: "Hands-on Exercises 3-2"
          href: "Hands-on_Ex/Hands-on_Ex03/hands_on3-2.html"
        - text: "Hands-on Exercises 4"
          href: "Hands-on_Ex/Hands-on_Ex04/hands_on4.html"
        - text: "Hands-on Exercises 5"
          href: "Hands-on_Ex/Hands-on_Ex05/hands_on5.html"
        - text: "Hands-on Exercises 6"
          href: "Hands-on_Ex/Hands-on_Ex06/hands_on6.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex08/hands_on8.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/hands_on10.html"
        - text: "Hands-on Exercise 11"
          href: "Hands-on_Ex/Hands-on_Ex11/hands_on11.html"
          
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/ICE_01/ice_01.html"
        - text: "In-class Exercise 2"
          href: "In-class_Ex/ICE_02/ice_02.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/ICE_03/ice_03.html"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/ICE_04/ice_04.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/ICE_05/ice_05.html"
        - text: "In-class Exercise 6"
          href: "In-class_Ex/ICE_06/ice_06.html"
        - text: "In-class Exercise 8"
          href: "In-class_Ex/ICE_08/ICE_08.html"
        - text: "In-class Exercise 10"
          href: "In-class_Ex/ICE_10/ice_10.html"
        - text: "In-class Exercise 11"
          href: "In-class_Ex/ICE_11/ice_11.qmd"
          
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercises 1"
          href: "Take-home_Ex/takehome_1.html"
        - text: "Take-home Exercises 2"
          href: "Take-home_Ex02/takehome_2.html"
        - text: "Take-home Exercises 3"
          href: "Take-home_Ex03/takehome_3.html"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

