project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercises 1"
          href: "Hands-on_Ex/Hands-on_Ex01/hands_on1.html"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

