---
title: "In-class Exercise 3"
author: "Javier Lian"
execute: 
  freeze: true
---

## Issue 1: Installing maptools

maptools is retired and binary is removed from CRAN. However, we can download from Posit Public Package Manager snapshots by using the code chunks below.

```{r}
# After the installation is completed, it is important to edit the code chunk as shown below in order to avoid maptools being download and install repetitively every time the Quarto document been rendered.
#| eval: false
#install.packages("maptools", repos = "https://packagemanager.posit.co/cran/2023-10-13")
```

```{r}
pacman::p_load(sf, raster, spatstat, tmap, tidyverse)
```

## Import Data File

```{r}
#acled_sf <- readr::read_csv("data/Myanmar/ACLED_Myanmar.csv") %>%
#  st_as_sf(coords = c( "longitude","latitude"), crs = 4326) %>%
#  st_transform(crs = 32647) %>%
#    mutate(event_date = dmy(event_date))
```

```{r}

#tmap_mode("view")
#acled_sf %>% filter(year == 2023 |
#                      event_type == 'Political Violence') %>%
#  tm_shape() + tm_dots()
#tmap_mode("plot")
```
